# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WMS_um.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cWMS_um.proto\x12\x06WMS_um\"\x17\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"&\n\rResponse_Code\x12\x15\n\rresponse_code\x18\x01 \x01(\x03\"\x1c\n\x07Request\x12\x11\n\tjwt_token\x18\x01 \x01(\t\"\x18\n\x05Reply\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x32\x8d\x01\n\x05WMSUm\x12<\n\x18RequestUserIdViaJWTToken\x12\x0f.WMS_um.Request\x1a\r.WMS_um.Reply\"\x00\x12\x46\n\x1dRequestDeleteUser_Constraints\x12\x0c.WMS_um.User\x1a\x15.WMS_um.Response_Code\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'WMS_um_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=24
  _globals['_USER']._serialized_end=47
  _globals['_RESPONSE_CODE']._serialized_start=49
  _globals['_RESPONSE_CODE']._serialized_end=87
  _globals['_REQUEST']._serialized_start=89
  _globals['_REQUEST']._serialized_end=117
  _globals['_REPLY']._serialized_start=119
  _globals['_REPLY']._serialized_end=143
  _globals['_WMSUM']._serialized_start=146
  _globals['_WMSUM']._serialized_end=287
# @@protoc_insertion_point(module_scope)
