apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: weather-app
data:
  #prometheus.rules: |-
  prometheus.yml: |-
    #  evaluation_interval: 5s
    #rule_files:
     # - /etc/prometheus/prometheus.rules
    #alerting:
    #  alertmanagers:
    #   - scheme: http
    #      static_configs:
    #        - targets:
    #            - "alertmanager.monitoring.svc:9093"
    scrape_configs:
      - job_name: 'wms'
        scrape_interval: 30s
        static_configs:
          - targets: ['wms-service:50051']
      - job_name: 'um'
        scrape_interval: 30s
        static_configs:
          - targets: ['um-service:50053']
