apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    name: prometheus-server-conf
  namespace: weather-app
data:
  prometheus.rules: |-
    groups:
      - name: weather
        rules:
          - record: UM_success_requests_total
            expr: UM_requests_total - UM_failure_requests_total
    
          - record: WMS_success_requests_total
            expr: WMS_requests_total - WMS_failure_requests_total
    
          - record: WORKER_success_requests_to_OpenWeather_total
            expr: WORKER_requests_to_OpenWeather_total - WORKER_error_request_OpenWeather_total
    
          - record: UM_requests_per_second_in_the_last_hour
            expr: rate(UM_requests_total[1h])
    
          - record: WMS_requests_per_second_in_the_last_hour
            expr: rate(WMS_requests_total[1h])
    
          - record: UM_success_requests_percentage
            expr: UM_success_requests_total / clamp_min(UM_requests_total, 1) * 100
    
          - record: WMS_success_requests_percentage
            expr: WMS_success_requests_total / clamp_min(WMS_requests_total, 1) * 100
    
          - record: WORKER_success_requests_to_OpenWeather_percentage
            expr: WORKER_success_requests_to_OpenWeather_total / clamp_min(WORKER_requests_to_OpenWeather_total, 1) * 100
    
          - record: WORKER_DB_avg_query_durations_nanoseconds
            expr: WORKER_query_durations_nanoseconds_DB_sum / clamp_min(WORKER_query_durations_nanoseconds_DB_count, 1)
    
          - record: WORKER_DB_median_query_durations_nanoseconds
            expr: histogram_quantile(0.5, sum(rate(WORKER_query_durations_nanoseconds_DB_bucket[5m])) by (le))
    
          - record: WORKER_DB_90_quantile_query_durations_nanoseconds
            expr: histogram_quantile(0.9, sum(rate(WORKER_query_durations_nanoseconds_DB_bucket[5m])) by (le))
    
          - record: NOTIFIER_DB_avg_query_durations_nanoseconds
            expr: NOTIFIER_query_durations_nanoseconds_DB_sum / clamp_min(NOTIFIER_query_durations_nanoseconds_DB_count, 1)
    
          - record: NOTIFIER_DB_median_query_durations_nanoseconds
            expr: histogram_quantile(0.5, sum(rate( NOTIFIER_query_durations_nanoseconds_DB_bucket[5m])) by (le))
    
          - record: NOTIFIER_DB_90_quantile_query_durations_nanoseconds
            expr:  histogram_quantile(0.9, sum(rate( NOTIFIER_query_durations_nanoseconds_DB_bucket[5m])) by (le))
    
          - record: UM_DB_avg_query_durations_nanoseconds
            expr: UM_query_durations_nanoseconds_DB_sum / clamp_min(UM_query_durations_nanoseconds_DB_count,1)
    
          - record: UM_DB_median_query_durations_nanoseconds
            expr:  histogram_quantile(0.5, sum(rate( UM_query_durations_nanoseconds_DB_bucket[5m])) by (le))
    
          - record: UM_DB_90_quantile_query_durations_nanoseconds
            expr: histogram_quantile(0.9, sum(rate( UM_query_durations_nanoseconds_DB_bucket[5m])) by (le))
    
          - record: WMS_DB_avg_query_durations_nanoseconds
            expr: WMS_query_durations_nanoseconds_DB_sum / clamp_min(WMS_query_durations_nanoseconds_DB_count,1)
    
          - record: WMS_DB_median_query_durations_nanoseconds
            expr: histogram_quantile(0.5, sum(rate(  WMS_query_durations_nanoseconds_DB_bucket[5m])) by (le))
    
          - record: WMS_DB_90_quantile_query_durations_nanoseconds
            expr: histogram_quantile(0.9, sum(rate(  WMS_query_durations_nanoseconds_DB_bucket[5m])) by (le))

  prometheus.yml: |-
    global:
      evaluation_interval: 30s
    rule_files:
      - /etc/prometheus/prometheus.rules
    scrape_configs:
      - job_name: 'wms'
        scrape_interval: 30s
        static_configs:
          - targets: ['wms-service:50051']
      - job_name: 'um'
        scrape_interval: 30s
        static_configs:
          - targets: ['um-service:50053']
      - job_name: 'worker'
        scrape_interval: 30s
        static_configs:
          - targets: ['worker-service:50055']
      - job_name: 'notifier'
        scrape_interval: 30s
        static_configs:
          - targets: ['notifier-service:50055']
      - job_name: cadvisor
        scrape_interval: 30s
        static_configs:
          - targets: ['cadvisor:8080']
