# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifier_um.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11notifier_um.proto\x12\x0bnotifier_um\"\x1a\n\x07Request\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\"\x16\n\x05Reply\x12\r\n\x05\x65mail\x18\x01 \x01(\t2H\n\nNotifierUm\x12:\n\x0cRequestEmail\x12\x14.notifier_um.Request\x1a\x12.notifier_um.Reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notifier_um_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=34
  _globals['_REQUEST']._serialized_end=60
  _globals['_REPLY']._serialized_start=62
  _globals['_REPLY']._serialized_end=84
  _globals['_NOTIFIERUM']._serialized_start=86
  _globals['_NOTIFIERUM']._serialized_end=158
# @@protoc_insertion_point(module_scope)
