version: '3.6'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - wheather_network
    restart: always
    volumes:
      - zookeeper_data_volume:/var/lib/zookeeper/data
      - zookeeper_log_volume:/var/lib/zookeeper/log
      - zookeeper_secrets_volume:/etc/zookeeper/secrets

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    expose:
      - "29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - wheather_network
    restart: always
    volumes:
      - kafka_secrets_volume:/etc/kafka/secrets
      - kafka_data_volume:/var/lib/kafka/data

  notifier_mysqlDB:
    image: mysql:latest
    container_name: notifier_mysqlDB
    secrets:
      - notifier_DB_root_psw
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/notifier_DB_root_psw
      MYSQL_DATABASE: notifier
    volumes:
      - notifier_volume:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - wheather_network
    restart: always

  notifier_service:
    container_name: notifier_service
    build:
      context: ../notifier_service
      dockerfile: Dockerfile
    image: notifier_service_image:latest
    depends_on:
      - notifier_mysqlDB
      - kafka
    expose:
      - "50000"
    secrets:
      - app_password
      - notifier_DB_root_psw
      - email
    environment:
      APP_PASSWORD: /run/secrets/app_password
      HOSTNAME: "notifier_mysqlDB"
      PORT: 3306
      USER: "root"
      PASSWORD: /run/secrets/notifier_DB_root_psw
      DATABASE: "notifier"
      EMAIL: /run/secrets/email
    networks:
      - wheather_network
    restart: always

  um_mysqlDB:
    image: mysql:latest
    container_name: um_mysqlDB
    secrets:
      - um_DB_root_psw
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/um_DB_root_psw
      MYSQL_DATABASE: um
    volumes:
      - um_volume:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - wheather_network
    restart: always

  um_service:
    container_name: um_service
    build:
      context: ../user_manager_service
      dockerfile: Dockerfile
    image: user_manager_service_image:latest
    depends_on:
      - um_mysqlDB
    expose:
      - "50001"
    secrets:
      - um_DB_root_psw
    environment:
      HOSTNAME: "um_mysqlDB"
      PORT: 3306
      USER: "root"
      PASSWORD: /run/secrets/um_DB_root_psw
      DATABASE: "um"
    networks:
      - wheather_network
    restart: always

  worker_mysqlDB:
    image: mysql:latest
    container_name: worker_mysqlDB
    secrets:
      - worker_DB_root_psw
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/worker_DB_root_psw
      MYSQL_DATABASE: worker
      WORKERID: 1
    volumes:
      - worker_volume:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - wheather_network
    restart: always

  worker_service:
    container_name: worker_service
    build:
      context: ../worker_service
      dockerfile: Dockerfile
    image: worker_service_image:latest
    depends_on:
      - worker_mysqlDB
      - kafka
    expose:
      - "50002"
    secrets:
      - worker_DB_root_psw
      - apikey
    environment:
      HOSTNAME: "worker_mysqlDB"
      PORT: 3306
      USER: "root"
      PASSWORD: /run/secrets/worker_DB_root_psw
      DATABASE: "worker"
      APIKEY: /run/secrets/apikey
    networks:
      - wheather_network
    restart: always

volumes:
  notifier_volume:
  um_volume:
  worker_volume:
  zookeeper_data_volume:
  zookeeper_log_volume:
  zookeeper_secrets_volume:
  kafka_secrets_volume:
  kafka_data_volume:

networks:
  wheather_network:

secrets:
  notifier_DB_root_psw:
    file: notifier_DB_root_psw.txt
  app_password:
    file: app_password.txt
  email:
    file: email.txt
  um_DB_root_psw:
    file: um_DB_root_psw.txt
  worker_DB_root_psw:
    file: worker_DB_root_psw.txt
  apikey:
    file: apikey.txt