global:
  evaluation_interval: 30s
rule_files:
  - /etc/prometheus/prometheus.rules
scrape_configs:
  - job_name: 'wms'
    scrape_interval: 30s
    static_configs:
      - targets: ['wms-service:50051']
  - job_name: 'um'
    scrape_interval: 30s
    static_configs:
      - targets: ['um-service:50053']
  - job_name: 'worker'
    scrape_interval: 30s
    static_configs:
      - targets: ['worker-service:50055']
  - job_name: 'notifier'
    scrape_interval: 30s
    static_configs:
      - targets: ['notifier-service:50055']
