kind: Service
apiVersion: v1
metadata:
  namespace: weather-app
  name: notifier-service
  labels:
    app: notifier-service
spec:
  ports:
    - name: prom-port
      protocol: TCP
      port: 50055
      targetPort: 50055
  selector:
    app: notifier
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifier-deployment
  namespace: weather-app
  labels:
    app: notifier-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifier
  template:
    metadata:
      labels:
        app: notifier
    spec:
      restartPolicy: Always
      containers:
        - name: notifier
          image: francesc00/notifier_service_image:base
          imagePullPolicy: Always
          ports:
            - name: prom-port
              containerPort: 50055
          volumeMounts:
            - name: notifier-db-root-psw
              mountPath: /run/secrets/notifier-db-root-psw
              readOnly: true
            - name: app-password
              mountPath: /run/secrets/app-password
              readOnly: True
            - name: email
              mountPath: /run/secrets/email
              readOnly: true
          env:
            - name: HOSTNAME
              value: "notifier-mysqldb-service"
            - name: PORT
              value: "3306"
            - name: USER
              value: "root"
            - name: PASSWORD
              value: /run/secrets/notifier-db-root-psw/psw
            - name: DATABASE
              value: "notifier"
            - name: EMAIL
              value: /run/secrets/email/psw
            - name: NOTIFIERID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: APP_PASSWORD
              value: /run/secrets/app-password/psw
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
      volumes:
        - name: notifier-db-root-psw
          secret:
            secretName: notifier-db-root-psw
        - name: email
          secret:
            secretName: email
        - name: app-password
          secret:
            secretName: app-password