kind: Service
apiVersion: v1
metadata:
  namespace: weather-app
  name: notifier-mysqlDB-service
  labels:
    app: notifier-mysqlDB-service
spec:
  ports:
    - port: 3306
  selector:
    app: notifier-mysqlDB
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notifier-mysqlDB-stateful-set
  namespace: weather-app
  labels:
    app: notifier-mysqlDB-stateful-set
spec:
  serviceName: "notifier-mysqlDB-service"
  replicas: 1
  selector:
    matchLabels:
      app: notifier-mysqlDB
  template:
    metadata:
      labels:
        app: notifier-mysqlDB
    spec:
      restartPolicy: Always
      containers:
        - name: notifier-mysqlDB
          image: mysql:latest
          imagePullPolicy: Always
          ports:
            - name: notifier-mysqlDB-port
              containerPort: 3306
          volumeMounts:
            - name: notifier-mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: notifier-DB-root-psw
              mountPath: /run/secrets/notifier-DB-root-psw
              readOnly: true
          env:
            - name: MYSQL_ROOT_PASSWORD_FILE
              value: /run/secrets/notifier-DB-root-psw
            - name: MYSQL_DATABASE
              value: "notifier"
      volumes:
        - name: notifier-DB-root-psw
          secret:
            secretName: notifier-DB-root-psw
  volumeClaimTemplates:
    - metadata:
        name: notifier-mysql-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi