kind: Service
apiVersion: v1
metadata:
  namespace: weather-app
  name: um-service
  labels:
    app: um-service
spec:
  ports:
    - name: notifier-port
      protocol: TCP
      port: 50051
      targetPort: 50051
    - name: wms-port
      protocol: TCP
      port: 50052
      targetPort: 50052
    - name: apigw-port
      protocol: TCP
      port: 50053
      targetPort: 50053
  selector:
    app: um
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: um-deployment
  namespace: weather-app
  labels:
    app: um-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: um
  template:
    metadata:
      labels:
        app: um
    spec:
      restartPolicy: Always
      containers:
        - name: um
          image: francesc00/user_manager_service_image:base
          imagePullPolicy: Always
          ports:
            - name: notifier-port
              containerPort: 50051
            - name: wms-port
              containerPort: 50052
            - name: apigw-port
              containerPort: 50053
          volumeMounts:
            - name: um-DB-root-psw
              mountPath: /run/secrets/um-DB-root-psw
              readOnly: true
          env:
          - name: HOSTNAME
            value: "um-mysqlDB-service"
          - name: PORT
            value: "3306"
          - name: USER
            value: "root"
          - name: PASSWORD
            value: /run/secrets/um-DB-root-psw
          - name: DATABASE
            value: "um"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: um-DB-root-psw
          secret:
            secretName: um-DB-root-psw