kind: Service
apiVersion: v1
metadata:
  namespace: weather-app
  name: worker-mysqldb-service
  labels:
    app: worker-mysqldb-service
spec:
  ports:
    - port: 3306
  selector:
    app: worker-mysqldb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: worker-mysqldb-stateful-set
  namespace: weather-app
  labels:
    app: worker-mysqldb-stateful-set
spec:
  serviceName: "worker-mysqldb-service"
  replicas: 1
  selector:
    matchLabels:
      app: worker-mysqldb
  template:
    metadata:
      labels:
        app: worker-mysqldb
    spec:
      restartPolicy: Always
      containers:
        - name: worker-mysqldb
          image: mysql:latest
          imagePullPolicy: Always
          ports:
            - name: worker-dbp
              containerPort: 3306
          volumeMounts:
            - name: worker-mysql-persistent-storage
              mountPath: /var/lib/mysql
            - name: worker-db-root-psw
              mountPath: /run/secrets/worker-db-root-psw
              readOnly: true
          env:
            - name: MYSQL_ROOT_PASSWORD_FILE
              value: /run/secrets/worker-db-root-psw/psw
            - name: MYSQL_DATABASE
              value: "worker"
      volumes:
        - name: worker-db-root-psw
          secret:
            secretName: worker-db-root-psw
  volumeClaimTemplates:
    - metadata:
        name: worker-mysql-persistent-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi