kind: Service
apiVersion: v1
metadata:
  namespace: weather-app
  name: worker-service
  labels:
    app: worker-service
spec:
  selector:
    app: worker
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  namespace: weather-app
  labels:
    app: worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      restartPolicy: Always
      containers:
        - name: worker
          image: francesc00/worker_service_image:base
          imagePullPolicy: Always
          volumeMounts:
            - name: worker-DB-root-psw
              mountPath: /run/secrets/worker-DB-root-psw
              readOnly: true
            - name: apikey
              mountPath: /run/secrets/apikey
              readOnly: True
          env:
            - name: HOSTNAME
              value: "worker-mysqlDB-service"
            - name: PORT
              value: "3306"
            - name: USER
              value: "root"
            - name: PASSWORD
              value: /run/secrets/worker-DB-root-psw
            - name: DATABASE
              value: "worker"
            - name: APIKEY
              value: /run/secrets/apikey
            - name: WORKERID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 300m
              memory: 512Mi
      volumes:
        - name: worker-DB-root-psw
          secret:
            secretName: worker-DB-root-psw
        - name: apikey
          secret:
            secretName: apikey