apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: weather-app
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      protocol: TCP
      name: zookeeper-port
      targetPort: 2181
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: zookeeper-stateful-set
  name: zookeeper-stateful-set
  namespace: weather-app
spec:
  serviceName: "zookeeper"
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      restartPolicy: Always
      containers:
        - image: confluentinc/cp-zookeeper:latest
          imagePullPolicy: Always
          name: zookeeper
          ports:
            - name: zookeeper-port
              containerPort: 2181
          volumeMounts:
            - mountPath: /var/lib/zookeeper/data
              name: zookeeper-data-volume
            - mountPath: /var/lib/zookeeper/log
              name: zookeeper-log-volume
            - mountPath: /etc/zookeeper/secrets
              name: zookeeper-secrets-volume
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
  volumeClaimTemplates:
    - metadata:
        name: zookeeper-data-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: zookeeper-log-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
    - metadata:
        name: zookeeper-secrets-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi